import json,csv
from pathlib import Path
R=Path(__file__).parent
# All venue/title links checked against primary publisher or author sources on 2026-09-29.
P=[]
def add(id,name,title,venue,year,url,code,scope,read):P.append(dict(id=id,name=name,title=title,venue=venue,year=year,paper_url=url,code_url=code,scope=scope,verification=read))
add('R01','DM-EFS','DM-EFS: Dynamically Multiplexed Expanded Features Set Form for Robust and Efficient Small Object Detection','ICCV',2025,'https://openaccess.thecvf.com/content/ICCV2025/html/Sharma_DM-EFS_Dynamically_Multiplexed_Expanded_Features_Set_Form_for_Robust_and_ICCV_2025_paper.html','','고해상도 특징·동적 선택','학회 원문 본문')
add('R02','YOLO small-object structure','A Universal Structure of YOLO Series Small Object Detection Models','ACCV',2024,'https://openaccess.thecvf.com/content/ACCV2024/html/Hu_A_Universal_Structure_of_YOLO_Series_Small_Object_Detection_Models_ACCV_2024_paper.html','','얕은 검출 경로·fusion','학회 abstract·PDF 도입부')
add('R03','FreqFusion','Frequency-aware Feature Fusion for Dense Image Prediction','IEEE TPAMI',2024,'https://arxiv.org/abs/2408.12879','https://github.com/Linwei-Chen/FreqFusion','특징 결합·경계 보존','저자 본문·공식 코드·게재 서지')
add('R04','SET','SET: Spectral Enhancement for Tiny Object Detection','CVPR',2025,'https://openaccess.thecvf.com/content/CVPR2025/html/Sun_SET_Spectral_Enhancement_for_Tiny_Object_Detection_CVPR_2025_paper.html','https://github.com/HuixinSun/SET','학습 시 배경 특징 조절','학회 본문 §3·공식 코드 안내')
add('R05','Position Gaussian Distribution','Feature Information Driven Position Gaussian Distribution Estimation for Tiny Object Detection','CVPR',2025,'https://openaccess.thecvf.com/content/CVPR2025/html/Bian_Feature_Information_Driven_Position_Gaussian_Distribution_Estimation_for_Tiny_Object_CVPR_2025_paper.html','','위치 보조 감독·특징 보강','학회 본문 §3·ablation')
add('R06','SR-TOD','Visible and Clear: Finding Tiny Objects in Difference Map','ECCV',2024,'https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/02515.pdf','https://github.com/Hiyuur/SR-TOD','재구성 차이 기반 특징 보강','학회 본문·저자 공개 초록')
add('R07','DNTR','A DeNoising FPN With Transformer R-CNN for Tiny Object Detection','IEEE TGRS',2024,'https://arxiv.org/abs/2406.05755','https://github.com/hoiliu-0801/DNTR','fusion noise·2단계 검출','저자 abstract·공식 코드 안내')
add('R08','UGS','Uncertainty-Aware Gradient Stabilization for Small Object Detection','ICCV',2025,'https://openaccess.thecvf.com/content/ICCV2025/html/Sun_Uncertainty-Aware_Gradient_Stabilization_for_Small_Object_Detection_ICCV_2025_paper.html','','위치 학습 안정화','학회 본문 §3·§4')
add('R09','TOLF','Noise-Robust Tiny Object Localization with Flows','Pattern Recognition',2026,'https://arxiv.org/abs/2601.00617','','라벨 노이즈에 대한 위치 강건성','저자 본문·출판사 DOI 10.1016/j.patcog.2026.113041')
add('R10','D-FINE','D-FINE: Redefine Regression Task of DETRs as Fine-grained Distribution Refinement','ICLR',2025,'https://proceedings.iclr.cc/paper_files/paper/2025/hash/6cf58a87e3097e7d1f9be3e8693a93de-Abstract-Conference.html','https://github.com/Peterande/D-FINE','분포 기반 반복 위치 보정·주 baseline','학회 본문은 이전 조사에서 확인·공식 구성 재확인')
add('R11','DQ-DETR','DQ-DETR: DETR with Dynamic Query for Tiny Object Detection','ECCV',2024,'https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/09775.pdf','https://github.com/hoiliu-0801/DQ-DETR','객체 수·밀도에 따른 query','학회 본문·공식 코드')
add('R12','DEIM','DEIM: DETR with Improved Matching for Fast Convergence','CVPR',2025,'https://openaccess.thecvf.com/content/CVPR2025/html/Huang_DEIM_DETR_with_Improved_Matching_for_Fast_Convergence_CVPR_2025_paper.html','https://github.com/Intellindust-AI-Lab/DEIM','matching·학습 recipe','학회 abstract·본문 도입·보충자료')
add('R13','RT-DETR','DETRs Beat YOLOs on Real-time Object Detection','CVPR',2024,'https://openaccess.thecvf.com/content/CVPR2024/html/Zhao_DETRs_Beat_YOLOs_on_Real-time_Object_Detection_CVPR_2024_paper.html','https://github.com/lyuwenyu/RT-DETR','효율적 다중 scale 검출·대조군','이전 조사 학회 원문·공식 코드')
add('R14','BDNet','BDNet:Bio-Inspired Dual-Backbone Small Object Detection Network','CVPR',2026,'https://openaccess.thecvf.com/content/CVPR2026/html/Guan_BDNetBio-Inspired_Dual-Backbone_Small_Object_Detection_Network_CVPR_2026_paper.html','','색상·경계 이중 backbone, 직접 적용 제외','학회 abstract·본문 파일 확보')
add('R15','DyFCLT','DyFCLT: Dynamic Frequency-Decoupled Cross-Modal Learning Transformer for Multimodal Tiny Object Detection','CVPR',2026,'https://openaccess.thecvf.com/content/CVPR2026/html/Li_DyFCLT_Dynamic_Frequency-Decoupled_Cross-Modal_Learning_Transformer_for_Multimodal_Tiny_Object_CVPR_2026_paper.html','','RGBT frequency, 직접 적용 제외','학회 abstract·본문 파일 확보')
add('R16','NS-FPN','Seeing Through the Noise: Improving Infrared Small Target Detection and Segmentation from Noise Suppression Perspective','CVPR',2026,'https://openaccess.thecvf.com/content/CVPR2026/papers/Yuan_Seeing_Through_the_Noise_Improving_Infrared_Small_Target_Detection_and_CVPR_2026_paper.pdf','','적외선 특징 노이즈 억제, 간접 근거','학회 PDF 도입·본문 파일 확보')
add('R17','BoltzFormer','Boltzmann Attention Sampling for Image Analysis with Small Objects','CVPR',2025,'https://openaccess.thecvf.com/content/CVPR2025/html/Zhao_Boltzmann_Attention_Sampling_for_Image_Analysis_with_Small_Objects_CVPR_2025_paper.html','https://github.com/microsoft/BoltzFormer','작은 영역의 attention sampling, 간접 근거','학회 abstract·본문 도입')
add('R18','Salience DETR','Salience DETR: Enhancing Detection Transformer with Hierarchical Salience Filtering Refinement','CVPR',2024,'https://openaccess.thecvf.com/content/CVPR2024/html/Hou_Salience_DETR_Enhancing_Detection_Transformer_with_Hierarchical_Salience_Filtering_Refinement_CVPR_2024_paper.html','https://github.com/xiuqhou/Salience-DETR','scale bias·후보 선택','학회 본문 §3·공식 코드')
add('R19','Detection calibration','Beyond Classification: Definition and Density-Based Estimation of Calibration in Object Detection','WACV',2024,'https://openaccess.thecvf.com/content/WACV2024/html/Popordanoska_Beyond_Classification_Definition_and_Density-Based_Estimation_of_Calibration_in_Object_WACV_2024_paper.html','','검출 신뢰도 평가','학회 서지·논문 초록')
add('R20','DiL','DiL: An Explainable and Practical Metric for Abnormal Uncertainty in Object Detection','WACV',2025,'https://openaccess.thecvf.com/content/WACV2025/html/Giloni_DiL_An_Explainable_and_Practical_Metric_for_Abnormal_Uncertainty_in_WACV_2025_paper.html','','미검출 포함 장면 수준 불확실성','학회 PDF abstract·도입')
add('R21','CRC detection','Conformal Risk Control for Pulmonary Nodule Detection','COPA / PMLR 266',2025,'https://proceedings.mlr.press/v266/hulsman25a.html','','민감도·FP trade-off, 보조 의사결정 근거','학회 abstract·적용 범위')
add('R22','QueryDet','QueryDet: Cascaded Sparse Query for Accelerating High-Resolution Small Object Detection','CVPR',2022,'https://openaccess.thecvf.com/content/CVPR2022/html/Yang_QueryDet_Cascaded_Sparse_Query_for_Accelerating_High-Resolution_Small_Object_Detection_CVPR_2022_paper.html','https://github.com/ChenhongyiYang/QueryDet-PyTorch','고해상도·후보 누락의 배경 연구','학회 abstract·본문 도입')
# Verified official DEIM entry used in this review; do not assume a renamed organization.
P[11]['code_url']='https://github.com/abinader96/DEIM'
(R/'papers.json').write_text(json.dumps(P,ensure_ascii=False,indent=2))
with (R/'papers.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.DictWriter(f,fieldnames=P[0].keys());w.writeheader();w.writerows(P)
